# Generated by Django 5.0 on 2023-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_realestateimage_rentalregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realestate",
            name="code",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
