# Generated by Django 5.0 on 2023-12-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_realestate_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=200, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="address",
            field=models.TextField(verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="code",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cód."),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="is_rented",
            field=models.BooleanField(default=False, verbose_name="Alugado?"),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AlterField(
            model_name="realestate",
            name="type",
            field=models.CharField(
                choices=[
                    ("Apartamento", "Apartamento"),
                    ("Kitnet", "Kitnet"),
                    ("Casa", "Casa"),
                ],
                max_length=100,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="rentalregister",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="rentalregister",
            name="end_date",
            field=models.DateTimeField(verbose_name="Data Fim"),
        ),
        migrations.AlterField(
            model_name="rentalregister",
            name="real_estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_register",
                to="myapp.realestate",
                verbose_name="Imóvel",
            ),
        ),
        migrations.AlterField(
            model_name="rentalregister",
            name="start_date",
            field=models.DateTimeField(verbose_name="Data Início"),
        ),
    ]
